### ISSUE TITLE
Update to 0.3.0 make encodarr to not working.

### ISSUE THREAD

**Issue by tr1p0p** [BrenekH/encodarr#109] opened 2021-08-07 12:46 UTC
So, doing update of encodarr runner + controller just make it not working.

Controller terminal show absolutely no errors.

Webapp get black for no reasons and runner show error and not encoding.

(Controller running on a arm64 raspebrry pi 4 on debian 10)

![bug](https://user-images.githubusercontent.com/37407065/128600568-31302793-4c9c-4d13-9b65-048da57abb00.jpg)

EDIT : weirdly, it's only the runners section that make the webapps goes dark. i can access to /settings /histories and all, but going to /running make him dark just after i click on it..

Also, my libraries settings (path, codec and all) get blank/empty Did i have like, to reset the config folder something like that ?
![emptylib](https://user-images.githubusercontent.com/37407065/128601240-25ffb496-61d4-431c-8ad5-8ac930c1826a.png)

**Comment by BrenekH** [comment] 2021-08-07 15:50
Could you upload the `data.db` and `data.db.backup` files from the config directory so I can check them out?

In the meantime, if you remove `data.db` (renaming it will do the trick) Encodarr should work again but you will need to re-setup the libraries.

**Comment by tr1p0p** [comment] 2021-09-09 10:15
Hi, sorry for the long answer time, was on vacations.

This is the upload of the data.db and data.db.backup [here](https://nullmoon.host/nullpload/f.php?h=2AqNGqCM&d=1) and [here](https://nullmoon.host/nullpload/f.php?h=0OkP51wT&d=1)

I'm go check if the trick you give me work.

Thks !

**Comment by tr1p0p** [comment] 2021-09-09 10:30
So, add library doesn't show ANY files queue, no progress bar, nothing.

Still doesn't know if it work. Here my config (that's worked before..)
![Screenshot 2021-09-09 at 12-30-11 Encodarr](https://user-images.githubusercontent.com/37407065/132670375-2023d99c-1fb6-4962-b460-67bd11931d89.png)

**Comment by BrenekH** [comment] 2021-09-09 16:01
So, just to clarify, after you add the new library, it doesn't pick up any new files to encode, correct?

**Comment by tr1p0p** [comment] 2021-09-10 11:51
Yeah it's exactly that, with the same config i was having before.

**Comment by BrenekH** [comment] 2021-09-10 13:48
Ok, go ahead and change the logs to Debug on the Settings page and that run for about 5 minutes or so. You can upload it here or take a look yourself, but they likely will describe why it isn't working.

**Comment by tr1p0p** [comment] 2021-09-10 21:16
Nothing show when i put controller in debug mode (even like 15 minutes after)..
![Capture d’écran du 2021-09-10 23-09-31](https://user-images.githubusercontent.com/37407065/132918027-7b702af5-b6f8-48d9-ad84-fd6c5d4a7c8c.png)

**Comment by BrenekH** [comment] 2021-09-10 22:27
Try looking in `<config dir>/controller.log`. I don't think the terminal will output the debug statements.

**Comment by tr1p0p** [comment] 2021-09-10 22:45
Ok, so, after i found controller was 2go size (!) i made a new controller.log and i found the problem, every item have this at the end  : `skipped because of a mask ()`

Remind me when i have the same error and i put something in "path mask" for library to make it actually work. I precise it make that on a totally new added library whit nothing touch.

**Comment by BrenekH** [comment] 2021-09-10 22:53
I don't think that's related to what happened to you on upgrade, so I'll go ahead and open a separate issue for the path masks thing. I'll take another look through the DB to see if I can find anything actionable. If I can't I'll just go ahead and close this.

**Comment by tr1p0p** [comment] 2021-09-10 22:57
Well, they're still a issue in the fact when i update to 0.3.0 my data.db get corrupted, i think. I suppose from the fact controller get rewritten. But yeah this issues deserve this own issue open.

**Comment by BrenekH** [comment] 2021-09-10 23:00
Yeah, Version 0.3.0 introduced a new database schema that I thought would migrate smoothly, but apparently not.

Like I said, I'll take another look to see if I can find the issue. But if not, I don't think there's much more that can be done here.

**Comment by BrenekH** [comment] 2021-09-11 01:56
Alright, I think I know what happened. The first screenshot is from the Runner's side, indicating that it didn't know what to do with the information the Controller was sending it. This is because the Runner API got a few tweaks in 0.3.0 that make it incompatible with Runner v0.2.x.

I'm still not sure what happened with the Runners screen in the WebUI. I'm not going to worry about it since it has fixed itself, and I can't replicate it with the db file on my machine.

Any other breakage was mostly caused by the move to a new column name for the library settings.

I think the most important thing to come out of this, is the understanding of a need for better communication about breaking changes. This will likely appear as a modal that appears on boot up of a new Controller version for the first time. And I would prefer that once Encodarr hits 1.0.0, any breaking changes get represented as a major version bump and are well thought out so that the end user has the least amount of friction as possible.

**Closed by BrenekH** 2021-09-11 01:56 UTC
Labels: bug
